version: '3'
services:
  redis:
    image: redis
    expose:
      - 6379
    volumes:
      - ./docker/redis:/data
  gokgs:
    build: .
    ports:
      - 8081:8081
    depends_on:
      - redis
    env_file: .env
